export const ascii = `
  &&&&&88888888888&&&&&&&&&&&&&&&&&&&8&8%%%8888&&&WWWWMMMMMMMMMMMMMMMMMMMMMMM
  ********###########MMMMMMMMMMWWWWWWWWW&88&WWMMM####***oooooaaaaaaa*******+*
  W&W&&&&&&&&&&&WoW&&&&WW&WWWWWWWWW&W&&&8888&&#WWWWWMMMMMMMMMM#M#M##########*
  WWWWWWWWWWWWWW*oMMMMMMMMMMMMMMMMMMMMMMW&&&WM#MMMMM#######******************
  aaaaooaooooooooooooooooooooo**ooo*****#MWWM###****ooooaaaa********++*++++++
  ****#############*#**##*########*######MWWWM#####****ooooooaaaaaaoaaaaaaa**
  WWWWWWWWWWWWM#MM***o**#############M#MMMWWWM####*M#************#***#***#oaa
  ############*oo****aoooooo**o***********#$W##**#@8&oooooaaaaaaaaaaaaaa*****
  aaoooooooooooaao*##aaa8$%MW#*aooooooooooB88#***#8&WMaaa*******+++++++++++++
  aooooooooooooooo###a#8B@8%&WWWWWoooooooo88&8#**#&&WWoaa****a#**+++++++++=++
  WWWWWWWWWWWWWMM####888%$8&MMMMM*########&&&&&****WWWW*****M8&*oo*oo***ooo*+
  ooaaMM#*##oaa*#oMM8@8$$$@BWWW&W&MM#**#*##WW&&W**aWWWW**a**%&W*o*#*oo****o*+
  aa*o##M#M*Ma*o*oWW*aaa*MWooaaao*MWM**B###WWW&&##o&WWWW*o*o8&WM#*ooo*##a***+
  ***oooooooa***a*+*+++*****W8o#a***a*%&WaaaWWW&&#oaWWWWa***8WWM*+++++*+++=*+
  ++****a*******+++++++***aa**&&&****M&&W&***W&&&&*aWWWWM*++8WWM++=========++
  *************++++++*aoooooaa**W&W***&WWW***W&&&&Ma*WWWW*++&WWM+==========+*
  ****++*****a++++++*ao**ooaaaaa*WWW#*MWWWW**aWWW&Wa*WWWWM+++WMM*===========a
  ***+********+==+=*aaooooaoooaaa*aWWM*WMMWM**WWWWWM*#MWWW+++WWWo==+========a
  *****+++**a+====***aaoooo***oaa*+*+++*MWWWo*#WWW&W*+WW&W+++&WW#===========a
  *aaoaaooaaa=====**aoooo*##*oa******+*a#WWWMoMM&&&&*a&&&W***&WW#+++++++++++a
  **o**###*#+====+*a****###*aao***o#+**o#WWWWMMM&&&&W*&&&&Maa&WM#o**aooa++**a
  **ao*#**##+====+*o***###*oo*##**ooa**=aWWWWWMW&&WW&*#WW&W+a&&W#oooooo*=+*oo
  a****aaaa*a====*aa*ao**oo***ooaa#*oo+=+oWWW&WW&&WW&&aWW&&*a&&W#*+*++*+++++*
  **++*aaooaa*===aao**#**o***o#oM#Mooo*++a*&&&&M&&&&&8B&&&&MM&WW#++=+==+=*==+
  a**+*aaooaaoaa**###oo*oooooo*MooMoooa+**oW&&&&&W&88888888%8&WW#+++++++=*=++
  aa*+*aaaaaa*o**#M#*aa*MMa##a*####*ooo++o**&&&&B@888888888888&WM+======*+=+=
  a**+aaaaaaaoo*ooM*#a**WM#o##M###W***o*Mo**MWW&888&&&&&&888888&W*+=++=+*++++
  aa+*aaaaaaaaa#a*W&M##WWW##*MMMMMM#**o+#o*aoW888&&&&&&&&&&&88&&W#++++++a++++
  &M*M*M&&&@WM@WW*#MW&&#8&###*##MM#*#*a*&o@@*W88&&&&&&&&&&&&&&&&WMMM&88a&MM#&
  W#M8##W@$$WB@@#M&W&WWM&WM####MM#***oa+**$$$%&&&&&&&&&&&&&&&&&WWMWW#8%&W$M##
  &#%Mo*M%8$M&WW&M&8&WMWM#*o*oMMWM#**oa+*&W&%B&&&&&&&&&&&&&8&&888W#M&B8B88#*W
  W&8o##BM8$$@&WW&##M&8WW**#o*##MM#**aa+-+M88&W&&&W&&&&8&88888%88WM%%B8%M##o#
  M#Mo8*MWWW@8W*WWWW&&&W&M#*#*#####**aa+-MMW&&M&8&&&&&88888888%8&WMM#&&8W8W#B
  W$&*%MWW#&MM&oWWW*W&&&WMWM#####*#&B@@=-=MM8&#8888&&&88888%88%88WM**#o&*%&8M
  8&&8MMW@&@&@&oWWWoMW&8W&#*o*ao##&W8&%B%#MMM%#&8&&&&&&8888888%%8&M#**a#*#W#o
  #B8&B%8###MWW+WWWoaM&&&#aMWWMMM#W&&&&&W8#*MM#%8&&&&&&88888%%%88&WM**a*W#*&W
  WMM%&M##W&8WM+WWMo=#W&WW&M##MM#**#W&&WW&%#MM#%88&&8&&88%%%%%%8&&WMa**#WWoM#
  *W8&&M&M#8W#8*WW**#*M&M&WW##MM#**oaWW&&&&%8WB%8&&88888%%%%%%%88&WMo**MoooWo
  M88$&%o#WMMMMMWWo**oMWMWWW##MM*oooa+*WW&&&&88&888888888%%%%%%88&WM*a@*#o**#
  ##MWW&W&W#W#&WMW**oaa*#MMWWWM#*oo*++*a&&&&&&88888888888%%%%%%88&WM#*o*o*Mo8
  *M#MWM*&M#WWo*oooaa*=a##MWWMM##oa*+**ao&88888%888888888%%B%%%88&WM*a#*ao#W#
  *W*MMo#M8M*oaaa====---oo*MMWM*Ma+*+*a*oo8888%88888&8888%%%%%888&WW#oo*oo#8#
  MMWM*aW&Maaa++=----::-:*a###*a*++****o*o#&88&888888&888%8%%88%8&&W##a#a+o*#
  ***##aWoa+**==----:::-:,***+===*aa*ao**o#*WW&&8888888&888888888&&WM#M#a*+*o
  *#*MWWoo*=*+------::::::W##o***aaaaa***o#*=W&&&888888&88888888&&&WMMMW#a+*o
  *a*o*oaa*-++-----:::::::aW***oooaaao##*o#=-=*W&&&&&8888888&&&&&&&WWMMWWo*o*
  aoo#oo**+-=+-----:::::::-W#**ooaooa###*o#--=*=#WW&&&&&8&&&&&&WWWWWWWMWW#o+*
  ao8***+++--=-:-:-::::::::WW#*aoooo*#M##o*::=*::=MWWWWWWWWWW&WWWWWW8&WMWW*ao
  MMoa**+=+-:=--:---:::::::-WMM#***##MM##*+::-+::++*#MM#MWMWW88&&W&888WWWW#**
  ooa*++=-=-:--::---:::::::-*WMM####WWM###::::-::+=++++a#MMW&&8%%8888%8M&WM#*
  oa**++=:--:---::--:::::::--oMMMM#MWWMM#*::::-,:+==+===*o#MW&888%%88%%WWWMM#
  a**+===:-=:-::-::-::::-::---a#M##MWWMM#::::::,-===+====++#MW888%%%88%8&&MW#
  *++++=+::-:-::::---::::::----*o#MW&&##::::::,,====+======+#M&88&%%%888&&MW#
  **====+::-:-:--:--::::::::----+a#MWM*::::::-::====+=======+oMW8888%8888&WWM
  ++=-===::-:-:::-:-::::::::--:-:----::,::::-:::--==+======++=*#&88888888&&&W
  +==----::::-::::::-::::::::--:::::::,,:::::-:::-==+======+=-=+M&8&888888&&&
  +==--=-:::::::::::-:::::::::-:::::::,,,,::::,,:-==+=====+==-=-*M&&&888888&&
  ===----:::::::::-:-::::::::::::::::,,,,,,::::,:--++======------+M&&&&&8&&&&
  +--::-:-:::::::::--:,::::::::::::::,,,:,,::,:::--+=======:::-:--=MWW&&&&&8&
`;
